# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asMatrix <- function(rp, cp, z, nrows, ncols) {
    .Call('_scatacr_asMatrix', PACKAGE = 'scatacr', rp, cp, z, nrows, ncols)
}

rowCorCpp <- function(idxX, idxY, X, Y) {
    .Call('_scatacr_rowCorCpp', PACKAGE = 'scatacr', idxX, idxY, X, Y)
}

tabulate2dCpp <- function(x1, xmin, xmax, y1, ymin, ymax) {
    .Call('_scatacr_tabulate2dCpp', PACKAGE = 'scatacr', x1, xmin, xmax, y1, ymin, ymax)
}

